# your domain
domain: example.com
port:             # default 12580

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# (optinal) postgresql database info
database_url: ""

# time duration between each execution
crontime:         # default 60

# (optinal) cloudflare api
cf_email: ""
cf_key: ""



# speedtest
speedtest: false  # default false. Warning: this will consume large net resource.
connection:       # default 5.
timeout:          # default 10 (seconds).
